In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])    #creating an array
a
# type(a)

array([1, 2, 3])

In [3]:
li=[1,2,3]
li
# type(li)

[1, 2, 3]

In [4]:
b=np.zeros((2,3))    #creating a metrix with column-2 & rows-3 with value-0
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
c=np.ones((3,2))   #to create a matrix with 2 dimensional & value-1
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
d=np.full((3,3),7)    #to create a matrix of any dimention including 3-Dimentions
d

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:
e=np.eye(3)         #to create identical matrix
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
f=np.arange(0,10,2)     #to create a set of numbers  from start-0 to end-10 with step=2
f

array([0, 2, 4, 6, 8])

In [9]:
 # linspace() allows you to specify the total number of points you want in the array, 
# and NumPy will calculate the spacing between the numbers automatically.


g=np.linspace(0,1,10)   #it generates an array of 10 numbers between 0 and 1, including both endpoints.
g

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
h=np.random.rand(3,3)    #to create random numbers matrix with given 
h

array([[0.04132984, 0.54421424, 0.29321083],
       [0.56947687, 0.95643031, 0.19861559],
       [0.11230425, 0.19932538, 0.86152778]])

In [11]:
# here,If no argument is given a single Python float is returned.

i=np.random.randn(3,3)    
i

array([[-1.3194657 ,  0.90671929, -1.49765863],
       [-0.01184109,  0.50664157, -2.76100318],
       [-0.48701572, -0.80615734, -0.78115098]])

In [12]:
j=np.random.randint(1,10,(2,2))   #to create a matix with any random number with 2X2 Dimentional
j

array([[4, 8],
       [1, 2]], dtype=int32)

In [13]:
print("\n=== Shape & Dimension ===")
print("shape :",b.shape)
print("size:",b.size)
print("Dimensions:",b.ndim)


=== Shape & Dimension ===
shape : (2, 3)
size: 6
Dimensions: 2


In [14]:
# The numpy.reshape() function is used to change the shape of a NumPy array without altering its underlying data. 


k=a.reshape(3,1)
k

array([[1],
       [2],
       [3]])

In [15]:
# The numpy.ravel() function in Python's NumPy library is used to flatten a multi-dimensional array into a one-dimensional array.

l=np.ravel(k)
l

array([1, 2, 3])

In [16]:
# n NumPy, transpose() is used to reorder the dimensions (axes) of an array if dimensions is 2X3 then it will convert it into 3X2

m=np.transpose(c)
m

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# The numpy.expand_dims() function in NumPy is used to add a new axis or dimension to an existing array. 

n=np.expand_dims(a,axis=0)
n

array([[1, 2, 3]])

In [18]:
print("\n=== Descriptive Statistics ===")
arr=[1,2,3,4,5]

mean=np.mean(arr)
print("Mean:",mean)

median=np.median(arr)
print("Median:",median)

variance=np.var(arr)
print("variance:",variance)

standard_variation=np.std(arr)
print("standard deviation:",standard_variation)

q1=np.percentile(arr,25)
print("Q1:",q1)

q2=np.percentile(arr,75)
print("Q2:",q2)



=== Descriptive Statistics ===
Mean: 3.0
Median: 3.0
variance: 2.0
standard deviation: 1.4142135623730951
Q1: 2.0
Q2: 4.0


In [19]:
print("\n=== Indexing & Slicing ===")
print("21. First element of a:", a[0])
print("22. Slice a[1:3]:", a[1:3])
print("23. Last element (a[-1]):", a[-1])


=== Indexing & Slicing ===
21. First element of a: 1
22. Slice a[1:3]: [2 3]
23. Last element (a[-1]): 3


In [20]:
print("\n=== Logical Operations ===")
mask=a>1
print("Boolean mask(a>1):",mask)


=== Logical Operations ===
Boolean mask(a>1): [False  True  True]


In [21]:
filtered=a[mask]
print("Filtered element (a>1):",filtered)

Filtered element (a>1): [2 3]


In [22]:
y=np.any(a>1)
print("Are all elements:",y)

Are all elements: True


In [23]:
z=np.all(a>1)
print("Are all elements:",z)

Are all elements: False


In [24]:
print("\n=== Aggregation & Utility Functions ===")
print("Max of a:", np.max(a))
print("Min of a:", np.min(a))
print("Argmax (index of max in a):", np.argmax(a))
print("Unique elements in a:",np.unique(a))



=== Aggregation & Utility Functions ===
Max of a: 3
Min of a: 1
Argmax (index of max in a): 2
Unique elements in a: [1 2 3]


In [25]:
# Difference between transpose & reshape ?
# -> Reshape allows you to transform your matrix into different shapes of your wish.
# Transpose compulsorily transforms a m*n matrix to n*m matrix by flipping rows to columns; 
# meaning the first row in the original matrix becomes the first column in the transposed matrix.

